import { defineStore } from 'pinia'
import { ref } from 'vue'

export interface Category {
  id: number
  name: string
  description?: string
  icon: string
  createdAt: Date
  startDate: Date | null
  endDate: Date | null
}

export const useCategoryStore = defineStore('category', () => {
  const selectedCategoryId = ref<number | null>(null)

  const categories = ref<Category[]>([
    {
      id: 0,
      name: 'Work',
      description: 'Tasks related to your job or career',
      icon: '💼',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 1,
      name: 'Personal',
      description: 'Personal development or routines',
      icon: '🏠',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 2,
      name: 'Fitness',
      description: 'Exercise and physical activity',
      icon: '🏋️‍♂️',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 3,
      name: 'Health',
      description: 'General health and wellness habits',
      icon: '🩺',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 4,
      name: 'Sleep',
      description: 'Sleep schedules and improvement',
      icon: '🛌',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 5,
      name: 'Nutrition',
      description: 'Healthy eating and food tracking',
      icon: '🥗',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 6,
      name: 'Hydration',
      description: 'Water and fluid intake',
      icon: '💧',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 7,
      name: 'Learning',
      description: 'Education and skill-building',
      icon: '📚',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 8,
      name: 'Reading',
      description: 'Reading books or articles',
      icon: '📖',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 9,
      name: 'Mindfulness',
      description: 'Meditation and awareness practices',
      icon: '🧘‍♂️',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 10,
      name: 'Journaling',
      description: 'Writing thoughts or reflections',
      icon: '📓',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 11,
      name: 'Gratitude',
      description: 'Practicing gratitude daily',
      icon: '🙏',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 12,
      name: 'Productivity',
      description: 'Efficiency and task completion',
      icon: '📈',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 13,
      name: 'Focus',
      description: 'Concentration and deep work',
      icon: '🎯',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 14,
      name: 'Budgeting',
      description: 'Tracking income and expenses',
      icon: '💵',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 15,
      name: 'Saving',
      description: 'Saving money or cutting costs',
      icon: '🏦',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 16,
      name: 'Spending',
      description: 'Being mindful of purchases',
      icon: '🛍️',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 17,
      name: 'Cleaning',
      description: 'Tidying and organizing spaces',
      icon: '🧹',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 18,
      name: 'Cooking',
      description: 'Home cooking and meal prep',
      icon: '🍳',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 19,
      name: 'Digital Detox',
      description: 'Limiting screen or social media time',
      icon: '📵',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 20,
      name: 'Stretching',
      description: 'Mobility and flexibility work',
      icon: '🤸‍♂️',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 21,
      name: 'Steps',
      description: 'Walking or step count tracking',
      icon: '🚶‍♂️',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 22,
      name: 'Hygiene',
      description: 'Daily grooming and cleanliness',
      icon: '🧼',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 23,
      name: 'Skin Care',
      description: 'Routine skin care habits',
      icon: '🧴',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 24,
      name: 'Mental Health',
      description: 'Supportive mental wellness habits',
      icon: '🧠',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 25,
      name: 'Social',
      description: 'Connecting with others',
      icon: '🗣️',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 26,
      name: 'Hobbies',
      description: 'Time spent on hobbies or crafts',
      icon: '🎨',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 27,
      name: 'Creativity',
      description: 'Writing, drawing, creating',
      icon: '✏️',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 28,
      name: 'Volunteering',
      description: 'Helping others or your community',
      icon: '🤝',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 29,
      name: 'Spirituality',
      description: 'Prayer or spiritual practices',
      icon: '🕊️',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 30,
      name: 'Pets',
      description: 'Caring for animals or pets',
      icon: '🐶',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 31,
      name: 'Nature',
      description: 'Spending time outdoors',
      icon: '🌳',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 32,
      name: 'Errands',
      description: 'Daily to-dos and responsibilities',
      icon: '🧾',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 33,
      name: 'Home Projects',
      description: 'DIY or improvement tasks',
      icon: '🛠️',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 34,
      name: 'Relationships',
      description: 'Improving personal connections',
      icon: '❤️',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 35,
      name: 'Language',
      description: 'Learning or practicing a language',
      icon: '🈶',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 36,
      name: 'Music',
      description: 'Playing or listening mindfully',
      icon: '🎵',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 37,
      name: 'Planning',
      description: 'Daily or weekly planning routines',
      icon: '🗓️',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 38,
      name: 'Goals',
      description: 'Reviewing or setting personal goals',
      icon: '🏁',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
    {
      id: 39,
      name: 'Reflection',
      description: 'Self-review or end-of-day reflection',
      icon: '🔍',
      createdAt: new Date(),
      startDate: null,
      endDate: null,
    },
  ])

  // Optional: Helper to get category by ID
  const getCategoryById = (id: number) => {
    return categories.value.find((c) => c.id === id) || null
  }

  // Optional: Set selected category
  const selectCategory = (id: number | null) => {
    selectedCategoryId.value = id
  }

  return {
    selectedCategoryId,
    categories,
    getCategoryById,
    selectCategory,
  }
})
